### ISSUE TITLE
Python 3.4 incompatible ErrorReturnCode constructor

### ISSUE THREAD

**Issue by PerFuchs** [amoffat/sh#321]
The initialization of sh.ErrorReturnCode with stdout or stderr as None does not work with Python 3.4,
because the str type in 3.4 has no function decode.

sh.ErrorReturnCode('test', None, None)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/pfuchs/env/lis1/lib/python3.4/site-packages/sh.py", line 196, in **init**
    (full_cmd, exc_stdout.decode(DEFAULT_ENCODING, "replace"),
AttributeError: 'str' object has no attribute 'decode'

**Comment by amoffat** [comment]
Thanks for reporting

**Comment by amoffat** [comment]
@PerFuchs do you remember how you were triggering this error?

**Comment by PerFuchs** [comment]
I guess this line: ´sh.ErrorReturnCode('test', None, None)´ should be enough to trigger it. 

Sorry, would try myself again, but I will not have a Linux until next month.

**Comment by amoffat** [comment]
Ok thanks.  I guess I am wondering then why you were instantiating `ErrorReturnCode` on its own?  I thought the original issue was that somewhere in sh.py, we were passing in `None`, but if it is just in user code, I would say "don't do that" :)

**Comment by PerFuchs** [comment]
Alright, I will check when I have access to my code again. Thanks for your time.

**Comment by amoffat** [comment]
No problem, just re-open when ready

**Comment by PerFuchs** [comment]
Being back from my holidays I had time to read up about this ticket in my code.

I tried to instantiate `ErrorReturnCode` on its own to mock a failed `sh.Command` in a test. To do so I wanted to raise a `ErrorReturnCode` myself. However I wasn't able to find suitable inputs for the parameter `stdout` and `stderr`.  Your code in `ErrorReturnCode.__init__`  has an if statement to handle `None` as input for `stdout` and `stderr`. That implied for me that `None` is a possible input, but this doesn't work in Python 3.4. Traceback is: 

`
 Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/pfuchs/env/lis2/lib/python3.4/site-packages/sh.py", line 196, in __init__
    (full_cmd, exc_stdout.decode(DEFAULT_ENCODING, "replace"),
AttributeError: 'str' object has no attribute 'decode'
`
Could you advise a better way to mock a failed `sh.Command` than raising `sh.ErrorReturnCode` myself?
What would be a valid input for `ErrorReturnCode` `stdout` and `stderr`?

Since your code implies `None` is a valid input, which is not working in reality, that might be an issue in your code as well.

**Comment by amoffat** [comment]
The short answer is no, there doesn't seem to be another way to mock a command that raises `ErrorReturnCode`.  I will try to make it easier for the next release though.

**Comment by PerFuchs** [comment]
That sounds good. What could I actually pass to the constructor? `sys.stdout` and `sys.stderr` lead to an error on my machinge, because the are `unsubscriptable`.

**Comment by amoffat** [comment]
@PerFuchs sorry it's taken so long to get back to this.  Just use empty strings.  It's going to be the way to instantiate ErrorReturnCode manually going forward

**Comment by PerFuchs** [comment]
That works for me, just got rid of some ugly lines in our testing code. Thanks a lot, highly appreciate it. After you told me, it feels like I should have had this idea ;)
